language: node_js
node_js:
  - "8"
  - "7"
before_script:
  - CI=true && npm test
script:
  - npm run build 
before_deploy:
  - pip install awscli --upgrade --user
  - aws s3 rm s3://www.harryganz.com --recursive --only-show-errors
deploy:
  on:
    branch: master
  provider:  s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.harryganz.com
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths /*
branches:
  only:
    - master
    - dev
