language: node_js
node_js:
  - "8"
  - "7"
before_script: 
  - CI=true && npm test
script:
  - npm run build 
deploy:
  on:
    branch: dev
  provider:  s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.harryganz.com
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
branches:
  only:
    - master
    - dev
